name: Build and profile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9     
      
    - name: Build
      run: nix develop '.#minuska' --command ./build-and-profile.sh

