name: Build and profile and CoqDoc

on:
  push:
    branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9     
      
    - name: Build
      run: nix develop '.#minuska' --command ./build-and-profile.sh

    - name: CoqDoc
      run: nix develop '.#minuska' --command make -C minuska/ html

    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'minuska/html'

